# Generated by Django 4.2.4 on 2024-01-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_foundersinfo_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='team_size',
            field=models.CharField(max_length=20),
        ),
    ]
